# Generated by Django 5.1.3 on 2026-01-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_result_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='coefficient',
        ),
        migrations.AddField(
            model_name='subject',
            name='totalPoints',
            field=models.IntegerField(default=20),
        ),
    ]
