# Generated by Django 6.0.3 on 2026-03-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_nni_and_teacher_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم بالعربية'),
        ),
    ]
