# Generated by Django 6.0 on 2025-12-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="roles",
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("professor", "Professor"),
                    ("student", "Student"),
                    ("secretary", "Secretary"),
                    ("user", "User"),
                ],
                default="user",
                help_text="User role in the system",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
